---

- name: Check compatibility with OS
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family in kubernetes_supported_os_family

- name: Setup required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Setup required sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/kubernetes.conf
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Disable swap for current session
  ansible.builtin.shell: swapoff -a

- name: Disable swap permanently, persist across reboots
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
  notify: Systemd reload

- name: Include installation tasks
  ansible.builtin.include_tasks: "install/{{ ansible_facts.os_family }}.yml"

- name: Configure crictl
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
